# analyze_entry.py - autogenerated placeholder

# 🧠 [AUTO-HOOKED] Entry Scoring Integration
from bot_modules.strategies.entry.entry_scoring import calculate_entry_score, is_confident_entry

def evaluate_entry_signals(rsi_signal, structure_signal, sentiment_signal, is_volatile):
    signals = {
        "rsi": rsi_signal,
        "structure": structure_signal,
        "sentiment": sentiment_signal,
        "is_volatile": is_volatile
    }
    score = calculate_entry_score(signals)
    print(f"[ENTRY SCORE] {score}/4")
    return is_confident_entry(score)
# 🧠 [AUTO-HOOKED]
