# direction_logic.py - autogenerated placeholder


def _determine_genius_direction(self, pro_analysis: Dict, genius_features: Dict, current_price: float) -> str:
        """GENIUS Direction Determination with advanced confluence"""
        bullish_score = 0
        bearish_score = 0
        confidence_multiplier = 1.0
        
        # Market regime (Weight: 3)
        regime_data = pro_analysis.get('market_regime', {})
        if regime_data.get('market_bias') == 'bullish':
            bullish_score += 3
        elif regime_data.get('market_bias') == 'bearish':
            bearish_score += 3
        
        # Pattern recognition (Weight: 3) - NEW
        pattern_data = genius_features.get('pattern_recognition', {})
        if pattern_data.get('bullish_count', 0) > pattern_data.get('bearish_count', 0) + 1:
            bullish_score += 3
        elif pattern_data.get('bearish_count', 0) > pattern_data.get('bullish_count', 0) + 1:
            bearish_score += 3
        
        # Multi-timeframe confluence (Weight: 3) - NEW
        confluence_data = genius_features.get('confluence', {})
        alignment = confluence_data.get('alignment_strength', 0)
        if alignment > 75:
            confidence_multiplier = 1.5
            short_bias = confluence_data.get('short_term_bias')
            if short_bias == 'uptrend':
                bullish_score += 3
            elif short_bias == 'downtrend':
                bearish_score += 3
        
        # Enhanced liquidity zones (Weight: 2)
        liquidity_data = pro_analysis.get('liquidity_zones', {})
        enhanced_bias = liquidity_data.get('enhanced_bias', 'neutral')
        if enhanced_bias in ['bullish', 'strong_bullish']:
            bullish_score += 2
        elif enhanced_bias in ['bearish', 'strong_bearish']:
            bearish_score += 2
        
        # Volume profile (Weight: 2) - NEW
        volume_data = genius_features.get('volume_profile', {})
        volume_bias = volume_data.get('profile_bias', 'neutral')
        if volume_bias in ['bullish', 'strong_bullish']:
            bullish_score += 2
        elif volume_bias in ['bearish', 'strong_bearish']:
            bearish_score += 2
        
        # Enhanced market structure (Weight: 2)
        structure_data = pro_analysis.get('market_structure', {})
        enhanced_bias = structure_data.get('enhanced_bias', 'neutral')
        if enhanced_bias == 'bullish':
            bullish_score += 2
        elif enhanced_bias == 'bearish':
            bearish_score += 2
        
        # Apply confidence multiplier
        bullish_score *= confidence_multiplier
        bearish_score *= confidence_multiplier
        
        # GENIUS Decision Logic - More stringent requirements
        min_score_threshold = 8  # Raised from 5
        score_difference_threshold = 3  # Minimum difference required
        
        if (bullish_score >= min_score_threshold and 
            bullish_score > bearish_score + score_difference_threshold):
            return 'LONG'
        elif (bearish_score >= min_score_threshold and 
              bearish_score > bullish_score + score_difference_threshold):
            return 'SHORT'
        else:
            return 'WAIT'