
from config.hybrid_loader import HybridConfig

config = HybridConfig()
entry_cfg = config.entry
exit_cfg = config.exit
risk_cfg = config.risk
telegram_cfg = config.telegram

# position_sizing.py - autogenerated placeholder


def _calculate_genius_position_size(self, score: float, kelly_data: Dict, pro_analysis: Dict, genius_features: Dict) -> Dict[str, float]:
        """GENIUS Position Sizing with advanced risk assessment"""
        base_kelly = kelly_data.get('kelly_percentage', 0.02)
        score_multiplier = score / 100
        
        # Risk adjustment based on confluence
        confluence_data = genius_features.get('confluence', {})
        alignment_strength = confluence_data.get('alignment_strength', 0) / 100
        
        # Pattern strength adjustment
        pattern_data = genius_features.get('pattern_recognition', {})
        pattern_strength = pattern_data.get('pattern_strength', 0) / 100
        
        # Volume confirmation adjustment
        volume_data = genius_features.get('volume_profile', {})
        volume_strength = volume_data.get('volume_strength', 0) / 100
        
        # Calculate genius multiplier
        genius_multiplier = (alignment_strength + pattern_strength + volume_strength) / 3
        genius_multiplier = max(0.5, min(genius_multiplier, 1.5))  # Cap between 0.5x and 1.5x
        
        # Smart position sizing based on real balance and market conditions
        real_balance = self.config.get('initial_balance', 100.0)
        # Note: market_volatility calculation moved to separate function
        
        # Dynamic risk caps based on balance (simplified for now)
        if real_balance < 20:
            max_risk_cap = 0.03  # 3%
        elif real_balance < 100:
            max_risk_cap = 0.04  # 4%
        elif real_balance < 500:
            max_risk_cap = 0.03  # 3%
        else:
            max_risk_cap = 0.025  # 2.5%

        # Fee-aware position sizing
        from modules.constants import get_fee_rate
        fee_rate = get_fee_rate()
        total_fee_pct = fee_rate * 2  # Entry + Exit fees
        
        # Adjust position size for fees - smaller positions when fees are high
        fee_adjustment = 1.0
        if total_fee_pct > 0.0016:  # High fees
            fee_adjustment = 0.8  # Reduce position size by 20%
        elif total_fee_pct < 0.0008:  # Low fees
            fee_adjustment = 1.1  # Increase position size by 10%
        
        # Enhanced Kelly-based position sizing
        # Kelly percentage is the primary driver
        kelly_based_size = base_kelly * score_multiplier
        
        # Apply genius multiplier for market conditions
        enhanced_size = kelly_based_size * genius_multiplier
        
        # Apply fee adjustment
        fee_adjusted_size = enhanced_size * fee_adjustment
        
        # Apply risk caps
        final_size = max(fee_adjusted_size, 0.003)  # Min 0.3%
        final_size = min(final_size, max_risk_cap)
        
        # Kelly dominance check - if Kelly suggests higher risk, use it (with caps)
        if base_kelly > 0.05 and score_multiplier > 0.7:  # Strong Kelly signal
            kelly_dominant_size = base_kelly * 0.8  # Use 80% of Kelly
            final_size = max(final_size, kelly_dominant_size)  # Kelly takes precedence
            final_size = min(final_size, max_risk_cap)  # But still respect caps
        
        # Auto leverage calculation - will be calculated in position_sizing module
        # This is just a placeholder, actual leverage will be calculated during trade execution
        final_leverage = 3.0  # Default moderate leverage
        
        return {
            'risk_percentage': final_size,
            'leverage': final_leverage,
            'kelly_suggested': base_kelly,
            'genius_multiplier': genius_multiplier,
            'score_multiplier': score_multiplier,
            'kelly_dominant': base_kelly > 0.05 and score_multiplier > 0.7,
            'kelly_percentage': base_kelly,
            'win_rate': kelly_data.get('win_rate', 0.6),
            'total_trades': kelly_data.get('total_trades', 0)
        }

def adjust_risk_by_equity(current_equity: float, initial_equity: float, base_risk_pct: float) -> float:
    """
    Kurangi risk jika equity turun, naikkan jika naik (secara moderat)
    """
    change = (current_equity - initial_equity) / initial_equity
    if change < -0.1:
        return base_risk_pct * 0.5  # Kurangi risiko
    elif change > 0.2:
        return base_risk_pct * 1.5  # Lebih agresif
    return base_risk_pct
