# --- rsi.py ---
from typing import List, Union
import logging

logger = logging.getLogger(__name__)

def rsi(prices: List[float], period: int = 14) -> Union[float, List[float]]:
    try:
        if len(prices) < period + 1:
            return 50.0
        deltas = [prices[i] - prices[i-1] for i in range(1, len(prices))]
        gains = [delta if delta > 0 else 0 for delta in deltas]
        losses = [-delta if delta < 0 else 0 for delta in deltas]
        avg_gain = sum(gains[:period]) / period
        avg_loss = sum(losses[:period]) / period
        for i in range(period, len(gains)):
            avg_gain = (avg_gain * (period - 1) + gains[i]) / period
            avg_loss = (avg_loss * (period - 1) + losses[i]) / period
        if avg_loss == 0:
            return 100.0
        rs = avg_gain / avg_loss
        return 100 - (100 / (1 + rs))
    except Exception as e:
        logger.error(f"Error calculating RSI: {e}")
        return 50.0


# --- sma.py ---
from typing import List
import logging

logger = logging.getLogger(__name__)

def sma(prices: List[float], period: int = 20) -> float:
    try:
        if len(prices) < period:
            return prices[-1] if prices else 0.0
        return sum(prices[-period:]) / period
    except Exception as e:
        logger.error(f"Error calculating SMA: {e}")
        return prices[-1] if prices else 0.0


# --- ema.py ---
from typing import List
import logging
from .sma import sma

logger = logging.getLogger(__name__)

def ema(prices: List[float], period: int = 20) -> float:
    try:
        if len(prices) < period:
            return sma(prices, len(prices))
        multiplier = 2 / (period + 1)
        ema_val = prices[0]
        for price in prices[1:]:
            ema_val = (price * multiplier) + (ema_val * (1 - multiplier))
        return ema_val
    except Exception as e:
        logger.error(f"Error calculating EMA: {e}")
        return prices[-1] if prices else 0.0


# --- bb_bands.py ---
from typing import List, Dict
import statistics
import logging

logger = logging.getLogger(__name__)

def bb_bands(prices: List[float], period: int = 20, std_dev: float = 2.0) -> Dict[str, float]:
    try:
        if len(prices) < period:
            mid = prices[-1] if prices else 0.0
            return {"upper": mid, "lower": mid, "mid": mid}
        mid = sum(prices[-period:]) / period
        std = statistics.stdev(prices[-period:])
        return {
            "upper": mid + std_dev * std,
            "lower": mid - std_dev * std,
            "mid": mid
        }
    except Exception as e:
        logger.error(f"Error calculating Bollinger Bands: {e}")
        mid = prices[-1] if prices else 0.0
        return {"upper": mid, "lower": mid, "mid": mid}


# --- trend.py ---
# trend.py - autogenerated placeholder


# --- volume.py ---
# volume.py - autogenerated placeholder


