# emergency_exit.py - autogenerated placeholder


def _check_emergency_exits(self, profit_pct: float, closes: List[float], volumes: List[float], entry_analysis: Dict = None) -> Dict:
        """Critical emergency exit conditions"""
        
        # 1. Hard Stop Loss (3% absolute limit)
        if profit_pct <= -0.03:
            return {
                "action": "close",
                "reason": f"🚨 EMERGENCY STOP: {profit_pct:.2%} - Capital Protection!",
                "urgency": "CRITICAL"
            }
        
        # 2. Flash Crash Detection
        if len(closes) >= 5:
            recent_drop = (closes[-1] - max(closes[-5:])) / max(closes[-5:])
            if recent_drop <= -0.02:  # 2% drop in 5 candles
                return {
                    "action": "close",
                    "reason": f"🚨 FLASH CRASH DETECTED: {recent_drop:.2%}",
                    "urgency": "CRITICAL"
                }
        
        # 3. Volume Spike + Price Drop (Panic selling)
        if len(volumes) >= 10:
            avg_volume = np.mean(volumes[-10:])
            current_volume = volumes[-1]
            volume_spike = current_volume / avg_volume if avg_volume > 0 else 1
            
            if volume_spike > 3.0 and profit_pct < -0.01:
                return {
                    "action": "close",
                    "reason": f"🚨 PANIC SELLING: Vol {volume_spike:.1f}x + Loss {profit_pct:.2%}",
                    "urgency": "CRITICAL"
                }
        
        # 4. Entry Confidence-Based Emergency
        if entry_analysis:
            entry_confidence = entry_analysis.get('confidence', 0)
            if entry_confidence < 30 and profit_pct <= -0.015:
                return {
                    "action": "close",
                    "reason": f"🚨 LOW CONFIDENCE EXIT: Entry {entry_confidence:.1f}% + Loss {profit_pct:.2%}",
                    "urgency": "HIGH"
                }
        
        return {"should_exit": False, "reason": "No emergency conditions"}