# hold_logic.py - autogenerated placeholder


def _get_hold_suggestion(self, profit_pct: float, hold_confidence: float) -> str:
        """Get suggestion for holding position"""
        if hold_confidence > 80:
            return "STRONG_HOLD"
        elif hold_confidence > 60:
            return "HOLD"
        elif hold_confidence > 40:
            return "WEAK_HOLD"
        else:
            return "CONSIDER_EXIT"