# momentum_exit.py - autogenerated placeholder


def _check_genius_momentum_exits(self, closes: List[float], volumes: List[float], side: str, profit_pct: float, entry_analysis: Dict = None) -> Dict:
        """Genius momentum reversal detection"""
        
        if len(closes) < 20:
            return {"should_exit": False, "reason": "Insufficient data for momentum analysis"}
        
        # Advanced RSI with momentum divergence
        rsi = SmartIndicators.rsi(closes)
        rsi_prev = SmartIndicators.rsi(closes[:-1]) if len(closes) > 14 else rsi
        
        # Price momentum
        price_momentum = (closes[-1] - closes[-10]) / closes[-10] if len(closes) >= 10 else 0
        
        # Volume momentum
        volume_momentum = 0
        if len(volumes) >= 10:
            recent_vol = np.mean(volumes[-5:])
            older_vol = np.mean(volumes[-10:-5])
            volume_momentum = (recent_vol - older_vol) / older_vol if older_vol > 0 else 0
        
        # Momentum exhaustion detection
        momentum_exhausted = False
        exhaustion_reason = ""
        
        if side == 'LONG':
            # Overbought with momentum divergence
            if rsi > 75 and rsi < rsi_prev and profit_pct > 0.005:
                momentum_exhausted = True
                exhaustion_reason = f"RSI divergence: {rsi:.1f}"
            
            # Price up but volume declining
            elif price_momentum > 0.01 and volume_momentum < -0.2 and profit_pct > 0.008:
                momentum_exhausted = True
                exhaustion_reason = "Volume divergence"
        
        else:  # SHORT
            # Oversold with momentum divergence
            if rsi < 25 and rsi > rsi_prev and profit_pct > 0.005:
                momentum_exhausted = True
                exhaustion_reason = f"RSI divergence: {rsi:.1f}"
            
            # Price down but volume declining
            elif price_momentum < -0.01 and volume_momentum < -0.2 and profit_pct > 0.008:
                momentum_exhausted = True
                exhaustion_reason = "Volume divergence"
        
        if momentum_exhausted:
            return {
                "action": "close",
                "reason": f"📊 MOMENTUM EXHAUSTION: {exhaustion_reason} + Profit {profit_pct:.2%}",
                "urgency": "MEDIUM"
            }
        
        return {"should_exit": False, "reason": "Momentum remains strong"}