# pattern_exit.py - autogenerated placeholder


def _check_genius_pattern_exits(self, highs: List[float], lows: List[float], opens: List[float], closes: List[float], volumes: List[float], side: str, profit_pct: float) -> Dict:
        """GENIUS Pattern-Based Exit Recognition"""
        
        if len(closes) < 10:
            return {"should_exit": False, "reason": "Insufficient data for pattern analysis"}
        
        # 1. Reversal Candlestick Patterns
        reversal_patterns = self._detect_exit_candlestick_patterns(highs[-10:], lows[-10:], opens[-10:], closes[-10:])
        
        if reversal_patterns and profit_pct > 0.003:  # Only exit with profit
            pattern_strength = len(reversal_patterns)
            if pattern_strength >= 2:  # Multiple reversal signals
                return {
                    "action": "close",
                    "reason": f"🔄 REVERSAL PATTERNS: {pattern_strength} signals + Profit {profit_pct:.2%}",
                    "urgency": "MEDIUM"
                }
        
        # 2. Exhaustion Patterns
        exhaustion_signal = self._detect_exhaustion_patterns(highs, lows, closes, volumes, side)
        if exhaustion_signal["is_exhausted"] and profit_pct > 0.005:
            return {
                "action": "close",
                "reason": f"😴 EXHAUSTION: {exhaustion_signal['pattern']} + Profit {profit_pct:.2%}",
                "urgency": "MEDIUM"
            }
        
        # 3. Double Top/Bottom at Profit
        double_pattern = self._detect_double_top_bottom_exit(highs, lows, side, profit_pct)
        if double_pattern["should_exit"]:
            return {
                "action": "close",
                "reason": f"🎯 {double_pattern['pattern'].upper()}: Perfect Exit + Profit {profit_pct:.2%}",
                "urgency": "LOW"
            }
        
        # 4. Divergence Patterns
        divergence = self._detect_genius_divergence(closes, volumes)
        if divergence["has_divergence"] and profit_pct > 0.008:
            return {
                "action": "close",
                "reason": f"📊 DIVERGENCE: {divergence['type']} + Profit {profit_pct:.2%}",
                "urgency": "MEDIUM"
            }
        
        return {"should_exit": False, "reason": "No exit patterns detected"}