from bot_modules.monitoring.equity_tracker import get_latest_equity
# profit_taking.py - autogenerated placeholder


def _check_genius_profit_taking(self, profit_pct: float, closes: List[float], volumes: List[float], side: str, position_size: float, entry_analysis: Dict = None) -> Dict:
        """Multi-level genius profit taking system"""
        
        # Get entry confidence for profit target adjustment
        entry_confidence = entry_analysis.get('confidence', 50) if entry_analysis else 50
        confidence_multiplier = 0.7 + (entry_confidence / 100) * 0.6  # 0.7x to 1.3x
        
        # Adaptive profit targets based on market conditions
        market_volatility = self._calculate_market_volatility(closes)
        volatility_multiplier = 0.8 + min(market_volatility * 2, 0.4)  # 0.8x to 1.2x
        
        # Dynamic profit levels
        profit_levels = [
            0.003 * confidence_multiplier * volatility_multiplier,  # Quick scalp
            0.006 * confidence_multiplier * volatility_multiplier,  # Conservative
            0.012 * confidence_multiplier * volatility_multiplier,  # Standard
            0.020 * confidence_multiplier * volatility_multiplier,  # Aggressive
            0.035 * confidence_multiplier * volatility_multiplier   # Moon shot
        ]
        
        # Partial profit taking logic
        for i, level in enumerate(profit_levels):
            if profit_pct >= level:
                # Check trend continuation for higher levels
                if i >= 2:  # For levels 3+ check trend strength
                    trend_strength = self._calculate_trend_continuation_probability(closes, volumes, side)
                    if trend_strength > 70:  # Strong trend continues
                        continue  # Don't exit yet
                
                # Special conditions for each level
                level_names = ["Quick Scalp", "Conservative", "Standard", "Aggressive", "Moon Shot"]
                level_confidence = [95, 85, 75, 65, 50][i]
                
                # Risk-reward optimization
                if i == 0:  # Quick scalp - always take
                    return {
                        "action": "close",
                        "reason": f"⚡ {level_names[i]}: {profit_pct:.2%} (Risk-Free)",
                        "urgency": "LOW"
                    }
                
                elif i == 1:  # Conservative - take if market shows weakness
                    if self._detect_market_weakness(closes, volumes):
                        return {
                            "action": "close",
                            "reason": f"🛡️ {level_names[i]}: {profit_pct:.2%} (Weakness Detected)",
                            "urgency": "LOW"
                        }
                
                elif i >= 2:  # Standard+ levels - use advanced logic
                    market_strength = self._assess_market_continuation_strength(closes, volumes, side)
                    if market_strength < level_confidence:
                        return {
                            "action": "close",
                            "reason": f"🎯 {level_names[i]}: {profit_pct:.2%} (Market Strength: {market_strength:.1f}%)",
                            "urgency": "LOW"
                        }
        
        return {"should_exit": False, "reason": "Profit targets not met or trend continuing"}