
from config.hybrid_loader import HybridConfig

config = HybridConfig()
entry_cfg = config.entry
exit_cfg = config.exit
risk_cfg = config.risk
telegram_cfg = config.telegram

from strategies.exit.trailing_stop import trailing_stop
# should_exit.py - autogenerated placeholder


def should_exit(self, position_data, current_price, klines_data, entry_analysis=None):
        """SUPER BRILLIANT Exit Analysis - Genius Level Risk Management"""
        try:
            entry_price = float(position_data.get('entryPrice', 0))
            side = position_data.get('positionSide', 'LONG')
            position_size = float(position_data.get('positionAmt', 0))
            
            if entry_price == 0:
                return {"action": "hold", "reason": "Invalid entry price"}
            
            # === Fee-aware profit percentage ===
            if side == 'LONG':
                profit_pct = (current_price - entry_price) / entry_price
            else:
                profit_pct = (entry_price - current_price) / entry_price

            # Kurangi biaya (taker fee dua kali: buka + tutup)
            total_fee_pct = get_fee_rate() * 2  # contoh: 0.08% → 0.16%
            profit_pct -= total_fee_pct
            
            # Extract comprehensive market data
            if klines_data and len(klines_data) >= 50:
                highs = [float(k[2]) for k in klines_data]
                lows = [float(k[3]) for k in klines_data]
                opens = [float(k[1]) for k in klines_data]
                closes = [float(k[4]) for k in klines_data]
                volumes = [float(k[5]) for k in klines_data]
            else:
                closes = [current_price]
                highs = lows = opens = volumes = [current_price]
            
            # 1. CRITICAL EMERGENCY STOPS (Highest Priority)
            emergency_exit = self._check_emergency_exits(profit_pct, closes, volumes, entry_analysis)
            if emergency_exit["should_exit"]:
                return emergency_exit
            
            # 2. GENIUS PATTERN-BASED EXITS - NEW SUPER FEATURE
            pattern_exit = self._check_genius_pattern_exits(highs, lows, opens, closes, volumes, side, profit_pct)
            if pattern_exit["should_exit"]:
                return pattern_exit
            
            # 3. DYNAMIC VOLATILITY-BASED STOPS - Enhanced
            volatility_exit = self._check_enhanced_volatility_stops(closes, highs, lows, entry_price, side, profit_pct, entry_analysis)
            if volatility_exit["should_exit"]:
                return volatility_exit
            
            # 4. MULTI-LEVEL SMART PROFIT TAKING - Genius Feature
            profit_exit = self._check_genius_profit_taking(profit_pct, closes, volumes, side, position_size, entry_analysis)
            if profit_exit["should_exit"]:
                return profit_exit
            
            # 5. MARKET STRUCTURE BREAK EXITS - Enhanced
            structure_exit = self._check_enhanced_structure_exits(closes, highs, lows, side, profit_pct, entry_analysis)
            if structure_exit["should_exit"]:
                return structure_exit
            
            # 6. SESSION & TIME-BASED EXITS - Enhanced
            session_exit = self._check_enhanced_session_exits(profit_pct, closes, volumes, entry_analysis)
            if session_exit["should_exit"]:
                return session_exit
            
            # 7. MOMENTUM REVERSAL EXITS - Genius Feature
            momentum_exit = self._check_genius_momentum_exits(closes, volumes, side, profit_pct, entry_analysis)
            if momentum_exit["should_exit"]:
                return momentum_exit
            
            # 8. CORRELATION & MARKET SENTIMENT EXITS - Advanced Feature
            sentiment_exit = self._check_market_sentiment_exits(closes, volumes, side, profit_pct)
            if sentiment_exit["should_exit"]:
                return sentiment_exit
            
            # 9. TRAILING STOP MANAGEMENT - Genius Dynamic System
            trailing_exit = trailing_stop(
            entry_price=entry_price,
            closes=closes,
            high_prices=highs,
            low_prices=lows,
            side=side,
            profit_pct=profit_pct,
            fee_pct=fee_pct,
            mode=config.get('trailing_mode', 'profit')current_price, entry_price, side, profit_pct, closes)
            if trailing_exit["should_exit"]:
                return trailing_exit
            
            # If no exit signal, return enhanced hold with confidence score
            hold_confidence = self._calculate_hold_confidence(profit_pct, closes, volumes, entry_analysis)
            
            return {
                "action": "hold",
                "reason": f"🟢 Hold Strong - P&L: {profit_pct:.2%} | Confidence: {hold_confidence:.1f}%",
                "urgency": "NONE",
                "hold_confidence": hold_confidence,
                "suggested_action": self._get_hold_suggestion(profit_pct, hold_confidence)
            }
            
        except Exception as e:
            logger.error(f"Error in genius exit analysis: {e}")
            return {"action": "hold", "reason": "Exit analysis error", "urgency": "NONE"}