# structure_exit.py - autogenerated placeholder


def _check_enhanced_structure_exits(self, closes: List[float], highs: List[float], lows: List[float], side: str, profit_pct: float, entry_analysis: Dict = None) -> Dict:
        """Enhanced market structure break detection"""
        
        if len(closes) < 30:
            return {"should_exit": False, "reason": "Insufficient data for structure analysis"}
        
        # Advanced structure analysis
        structure_data = self.structure_analyzer.analyze_market_structure(closes)
        structure = structure_data.get('structure', '')
        
        # Key level breaks
        key_levels = self._identify_critical_levels(highs, lows, closes)
        current_price = closes[-1]
        
        # Structure break with confirmation
        structure_broken = False
        break_reason = ""
        
        if side == 'LONG':
            # Look for bearish structure breaks
            if structure in ['lower_highs_lower_lows']:
                structure_broken = True
                break_reason = "Bearish structure confirmed"
            
            # Support level breaks
            for level in key_levels:
                if level['type'] == 'support' and current_price < level['price'] * 0.998:
                    if profit_pct > 0.002:  # Only exit with some profit
                        structure_broken = True
                        break_reason = f"Support break at {level['price']:.6f}"
                        break
        
        else:  # SHORT
            # Look for bullish structure breaks
            if structure in ['higher_highs_higher_lows']:
                structure_broken = True
                break_reason = "Bullish structure confirmed"
            
            # Resistance level breaks
            for level in key_levels:
                if level['type'] == 'resistance' and current_price > level['price'] * 1.002:
                    if profit_pct > 0.002:  # Only exit with some profit
                        structure_broken = True
                        break_reason = f"Resistance break at {level['price']:.6f}"
                        break
        
        if structure_broken:
            # Volume confirmation
            volume_confirmation = self._check_volume_confirmation(closes, volumes if len(volumes) > 0 else [1])
            urgency = "MEDIUM" if volume_confirmation else "LOW"
            
            return {
                "action": "close",
                "reason": f"🏗️ STRUCTURE BREAK: {break_reason} + Profit {profit_pct:.2%}",
                "urgency": urgency
            }
        
        return {"should_exit": False, "reason": "Market structure intact"}