# volatility_exit.py - autogenerated placeholder


def _check_enhanced_volatility_stops(self, closes: List[float], highs: List[float], lows: List[float], entry_price: float, side: str, profit_pct: float, entry_analysis: Dict = None) -> Dict:
        """Enhanced volatility-based dynamic stops"""
        
        if len(closes) < 20:
            base_stop = -0.02
        else:
            # Advanced ATR calculation
            true_ranges = []
            for i in range(1, len(closes)):
                high_low = highs[i] - lows[i]
                high_close = abs(highs[i] - closes[i-1])
                low_close = abs(lows[i] - closes[i-1])
                true_range = max(high_low, high_close, low_close)
                true_ranges.append(true_range)
            
            atr = np.mean(true_ranges[-14:]) if len(true_ranges) >= 14 else np.mean(true_ranges)
            volatility_pct = (atr / closes[-1]) * 100
            
            # Genius volatility-based stop calculation
            if volatility_pct > 3.0:
                base_stop = -0.025  # Wider stop for high volatility
            elif volatility_pct > 2.0:
                base_stop = -0.02
            elif volatility_pct < 0.5:
                base_stop = -0.015  # Tighter stop for low volatility
            else:
                base_stop = -0.018
            
            # Market regime adjustment
            market_trend = self._get_market_trend_strength(closes[-50:] if len(closes) >= 50 else closes)
            if market_trend == 'strong_trend':
                base_stop *= 1.2  # Wider stops in trending markets
            elif market_trend == 'choppy':
                base_stop *= 0.8  # Tighter stops in choppy markets
        
        # Entry confidence adjustment
        if entry_analysis:
            confidence = entry_analysis.get('confidence', 50)
            confidence_multiplier = 0.8 + (confidence / 100) * 0.4  # 0.8x to 1.2x
            base_stop *= confidence_multiplier
        
        # Profit protection adjustment
        if profit_pct > 0.01:  # If in 1%+ profit, allow wider stop
            base_stop *= 1.3
        
        final_stop = max(base_stop, -0.03)  # Never more than 3%
        
        if profit_pct <= final_stop:
            return {
                "action": "close",
                "reason": f"📉 SMART STOP: {profit_pct:.2%} (ATR-based: {final_stop:.2%})",
                "urgency": "HIGH"
            }
        
        return {"should_exit": False, "reason": "Volatility stop not triggered"}